teams = [
 {
   "team": "Arizona Cardinals",
   "moniker": ['Arizona', 'Cardinals'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC West",
   "stadium": "State Farm Stadium",
   "location": "Glendale, Arizona",
   "longitude": -112.263,
   "latitude": 33.5276,
   "website": "https://www.azcardinals.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Buffalo Bills",
   "moniker": ['Buffalo', 'Bills'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC East",
   "stadium": "Highmark Stadium",
   "location": "Orchard Park, New York",
   "longitude": -78.787,
   "latitude": 42.7738,
   "website": "https://www.buffalobills.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Carolina Panthers",
   "moniker": ['Carolina', 'Panthers'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC South",
   "stadium": "Bank of America Stadium",
   "location": "Charlotte, North Carolina",
   "longitude": -80.8537,
   "latitude": 35.2251,
   "website": "https://www.panthers.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Miami Dolphins",
   "moniker": ['Miami', 'Dolphins'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC East",
   "stadium": "Hard Rock Stadium",
   "location": "Miami Gardens, Florida",
   "longitude": -80.2389,
   "latitude": 25.957,
   "website": "https://www.miamidolphins.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg",
   "affiliate": ""
 },
 {
   "team": "New England Patriots",
   "moniker": ['New England', 'Patriots'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC East",
   "stadium": "Gillette Stadium",
   "location": "Foxborough, Massachusetts",
   "longitude": -71.2643,
   "latitude": 42.0909,
   "website": "https://www.patriots.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Philadelphia Eagles",
   "moniker": ['Philadelphia', 'Philly', 'Eagles'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC East",
   "stadium": "Lincoln Financial Field",
   "location": "Philadelphia, Pennsylvania",
   "longitude": -75.1674,
   "latitude": 39.9008,
   "website": "https://www.philadelphiaeagles.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Atlanta Falcons",
   "moniker": ['Atlanta', 'Falcons'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC South",
   "stadium": "Mercedes-Benz Stadium",
   "location": "Atlanta, Georgia",
   "longitude": -84.4011,
   "latitude": 33.7554,
   "website": "https://www.atlantafalcons.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Baltimore Ravens",
   "moniker": ['Baltimore', 'Ravens'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC North",
   "stadium": "M&T Bank Stadium",
   "location": "Baltimore, Maryland",
   "longitude": -76.6227,
   "latitude": 39.278,
   "website": "https://www.baltimoreravens.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Chicago Bears",
   "moniker": ['Chicago', 'Bears'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC North",
   "stadium": "Soldier Field",
   "location": "Chicago, Illinois",
   "longitude": -87.6166,
   "latitude": 41.8623,
   "website": "https://www.chicagobears.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/1/15/Chicago_Bears_logo_primary.svg",
   "affiliate": ""
 },
 {
   "team": "Cincinnati Bengals",
   "moniker": ['Cincinnati', 'Bengals'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC North",
   "stadium": "Paul Brown Stadium",
   "location": "Cincinnati, Ohio",
   "longitude": -84.516,
   "latitude": 39.095,
   "website": "https://www.bengals.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Cleveland Browns",
   "moniker": ['Cleveland', 'Browns'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC North",
   "stadium": "FirstEnergy Stadium",
   "location": "Cleveland, Ohio",
   "longitude": -81.6954,
   "latitude": 41.5066,
   "website": "https://www.clevelandbrowns.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Dallas Cowboys",
   "moniker": ['Dallas', 'Cowboys'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC East",
   "stadium": "AT&T Stadium",
   "location": "Arlington, Texas",
   "longitude": -97.0929,
   "latitude": 32.7473,
   "website": "https://www.dallascowboys.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg",
   "affiliate": ""
 },
 {
   "team": "Denver Broncos",
   "moniker": ['Denver', 'Broncos'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC West",
   "stadium": "Empower Field at Mile High",
   "location": "Denver, Colorado",
   "longitude": -105.0201,
   "latitude": 39.7439,
   "website": "https://www.denverbroncos.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Detroit Lions",
   "moniker": ['Detroit', 'Lions'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC North",
   "stadium": "Ford Field",
   "location": "Detroit, Michigan",
   "longitude": -83.0458,
   "latitude": 42.3401,
   "website": "https://www.detroitlions.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Green Bay Packers",
   "moniker": ['Green Bay', 'Packers'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC North",
   "stadium": "Lambeau Field",
   "location": "Green Bay, Wisconsin",
   "longitude": -88.0634,
   "latitude": 44.5013,
   "website": "https://www.packers.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Houston Texans",
   "moniker": ['Houston', 'Texans'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC South",
   "stadium": "NRG Stadium",
   "location": "Houston, Texas",
   "longitude": -95.4109,
   "latitude": 29.6847,
   "website": "https://www.houstontexans.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Indianapolis Colts",
   "moniker": ['Indianapolis', 'Indy', 'Colts'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC South",
   "stadium": "Lucas Oil Stadium",
   "location": "Indianapolis, Indiana",
   "longitude": -86.1646,
   "latitude": 39.7601,
   "website": "https://www.colts.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Jacksonville Jaguars",
   "moniker": ['Jacksonville', 'Jaguars'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC South",
   "stadium": "TIAA Bank Field",
   "location": "Jacksonville, Florida",
   "longitude": -81.638,
   "latitude": 30.3241,
   "website": "https://www.jaguars.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Kansas City Chiefs",
   "moniker": ['Kansas City', 'Chiefs'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC West",
   "stadium": "Arrowhead Stadium",
   "location": "Kansas City, Missouri",
   "longitude": -94.4839,
   "latitude": 39.0517,
   "website": "https://www.chiefs.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Las Vegas Raiders",
   "moniker": "['Las Vegas', 'Vegas', 'Raiders']",
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC West",
   "stadium": "Allegiant Stadium",
   "location": "Paradise, Nevada",
   "longitude": -115.1541,
   "latitude": 36.0907,
   "website": "https://www.raiders.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/48/Las_Vegas_Raiders_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Los Angeles Chargers",
   "moniker": ['Los Angeles', 'LA', 'Chargers'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC West",
   "stadium": "SoFi Stadium",
   "location": "Inglewood, California",
   "longitude": -118.3287,
   "latitude": 33.9534,
   "website": "https://www.chargers.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Los_Angeles_Chargers_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Los Angeles Rams",
   "moniker": ['Log Angeles', 'LA', 'LA Rams', 'Rams'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC West",
   "stadium": "SoFi Stadium",
   "location": "Inglewood, California",
   "longitude": -118.3287,
   "latitude": 33.9534,
   "website": "https://www.therams.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Minnesota Vikings",
   "moniker": ['Minnesota', 'Vikings'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC North",
   "stadium": "U.S. Bank Stadium",
   "location": "Minneapolis, Minnesota",
   "longitude": -93.2667,
   "latitude": 44.9738,
   "website": "https://www.vikings.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg",
   "affiliate": ""
 },
 {
   "team": "New Orleans Saints",
   "moniker": ['New Orleans', 'Saints'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC South",
   "stadium": "Caesars Superdome",
   "location": "New Orleans, Louisiana",
   "longitude": -90.081,
   "latitude": 29.9511,
   "website": "https://www.neworleanssaints.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg",
   "affiliate": ""
 },
 {
   "team": "New York Giants",
   "moniker": ['New York', 'NY', 'Giants'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC East",
   "stadium": "MetLife Stadium",
   "location": "East Rutherford, New Jersey",
   "longitude": -74.074,
   "latitude": 40.812,
   "website": "https://www.giants.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg",
   "affiliate": ""
 },
 {
   "team": "New York Jets",
   "moniker": ['New York', 'NY', 'Jets'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC East",
   "stadium": "MetLife Stadium",
   "location": "East Rutherford, New Jersey",
   "longitude": -74.074,
   "latitude": 40.812,
   "website": "https://www.newyorkjets.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/6/69/New_York_Jets_2024.svg",
   "affiliate": ""
 },
 {
   "team": "Pittsburgh Steelers",
   "moniker": ['Pittsburgh', 'Steelers'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC North",
   "stadium": "Heinz Field",
   "location": "Pittsburgh, Pennsylvania",
   "longitude": -80.0164,
   "latitude": 40.4468,
   "website": "https://www.steelers.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg",
   "affiliate": ""
 },
 {
   "team": "San Francisco 49ers",
   "moniker": ['San Francisco', '49ers', 'Forty Niners', 'Niners', 'Forty-Niners', '49'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC West",
   "stadium": "Levi's Stadium",
   "location": "Santa Clara, California",
   "longitude": -121.9697,
   "latitude": 37.403,
   "website": "https://www.49ers.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Seattle Seahawks",
   "moniker": ['Seattle', 'Seahawks'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC West",
   "stadium": "Lumen Field",
   "location": "Seattle, Washington",
   "longitude": -122.3316,
   "latitude": 47.5952,
   "website": "https://www.seahawks.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Tampa Bay Buccaneers",
   "moniker": ['Tampa Bay', 'Tampa', 'Buccaneers', 'Buccs'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC South",
   "stadium": "Raymond James Stadium",
   "location": "Tampa, Florida",
   "longitude": -82.5048,
   "latitude": 27.9759,
   "website": "https://www.buccaneers.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Tennessee Titans",
   "moniker": ['Tennessee', 'Titans'],
   "league": "NFL",
   "conference": "AFC",
   "division": "AFC South",
   "stadium": "Nissan Stadium",
   "location": "Nashville, Tennessee",
   "longitude": -86.77,
   "latitude": 36.1664,
   "website": "https://www.tennesseetitans.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Washington Commanders",
   "moniker": ['Washington', 'DC', 'Commanders'],
   "league": "NFL",
   "conference": "NFC",
   "division": "NFC East",
   "stadium": "FedExField",
   "location": "Landover, Maryland",
   "longitude": -76.8644,
   "latitude": 38.9076,
   "website": "https://www.commanders.com/",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Washington_Commanders_logo.svg",
   "affiliate": ""
 },
 {
   "team": "Arlington Renegades",
   "moniker": ['Arlington', 'Renegades'],
   "league": "UFL",
   "conference": "XFL",
   "division": "N/A",
   "stadium": "Choctaw Stadium",
   "location": "Arlington, Texas",
   "longitude": -97.097,
   "latitude": 32.7357,
   "website": "https://www.theufl.com/teams/arlington",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/2/21/Arlington_Renegades_logo.png",
   "affiliate": ""
 },
 {
   "team": "Birmingham Stallions",
   "moniker": ['Birmingham', 'Stallions'],
   "league": "UFL",
   "conference": "USFL",
   "division": "N/A",
   "stadium": "Protective Stadium",
   "location": "Birmingham, Alabama",
   "longitude": -86.8114,
   "latitude": 33.5074,
   "website": "https://www.theufl.com/teams/birmingham",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/9a/Birmingham_Stallions_logo.svg",
   "affiliate": ""
 },
 {
   "team": "DC Defenders",
   "moniker": ['Washington DC', 'DC', 'D.C.', 'Washington D.C.', 'Defenders'],
   "league": "UFL",
   "conference": "XFL",
   "division": "N/A",
   "stadium": "Audi Field",
   "location": "Washington, D.C.",
   "longitude": -77.0126,
   "latitude": 38.8765,
   "website": "https://www.theufl.com/teams/dc",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/a/aa/DC_Defenders_logo.png",
   "affiliate": ""
 },
 {
   "team": "Houston Roughnecks",
   "moniker": ['Houston', 'Roughnecks'],
   "league": "UFL",
   "conference": "USFL",
   "division": "N/A",
   "stadium": "Rice Stadium",
   "location": "Houston, Texas",
   "longitude": -95.4027,
   "latitude": 29.7184,
   "website": "https://www.theufl.com/teams/houston",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/d/d9/Houston_Roughnecks_logo_%282022%29.png",
   "affiliate": ""
 },
 {
   "team": "Memphis Showboats",
   "moniker": ['Memphis', 'Showboats'],
   "league": "UFL",
   "conference": "USFL",
   "division": "N/A",
   "stadium": "Simmons Bank Liberty Stadium",
   "location": "Memphis, Tennessee",
   "longitude": -90.0495,
   "latitude": 35.1385,
   "website": "https://www.theufl.com/teams/memphis",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/c/c4/Memphis_Showboats.png",
   "affiliate": ""
 },
 {
   "team": "Michigan Panthers",
   "moniker": ['Michigan', 'Panthers'],
   "league": "UFL",
   "conference": "USFL",
   "division": "N/A",
   "stadium": "Ford Field",
   "location": "Detroit, Michigan",
   "longitude": -83.0458,
   "latitude": 42.3401,
   "website": "https://www.theufl.com/teams/michigan",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/7/71/Michigan_Panthers_transparent.png",
   "affiliate": ""
 },
 {
   "team": "San Antonio Brahmas",
   "moniker": ['San Antonio', 'Brahmas'],
   "league": "UFL",
   "conference": "XFL",
   "division": "N/A",
   "stadium": "Alamodome",
   "location": "San Antonio, Texas",
   "longitude": -98.4786,
   "latitude": 29.4167,
   "website": "https://www.theufl.com/teams/san-antonio",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/2/22/San_Antonio_Brahmas_logo.png",
   "affiliate": ""
 },
 {
   "team": "St. Louis Battlehawks",
   "moniker": ['St. Louis', 'St Louis', 'Battlehawks'],
   "league": "UFL",
   "conference": "XFL",
   "division": "N/A",
   "stadium": "The Dome at America's Center",
   "location": "St. Louis, Missouri",
   "longitude": -90.2003,
   "latitude": 38.6327,
   "website": "https://www.theufl.com/teams/st-louis",
   "sport": "Football",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/9c/St._Louis_Battlehawks_logo.png",
   "affiliate": ""
 },
 {
   "team": "Anaheim Ducks",
   "moniker": ['Ducks', 'Anaheim'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "Honda Center",
   "location": "Anaheim, California, USA",
   "longitude": -117.8761,
   "latitude": 33.8075,
   "website": "https://www.nhl.com/ducks",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/95/Anaheim_Ducks_logo_2024.svg",
   "affiliate": "San Diego Gulls (AHL)"
 },
 {
   "team": "Utah Hockey Club",
   "moniker": ['Utah', 'Hockey Club'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "Delta Center",
   "location": "Salt Lake City, Utah",
   "longitude": -111.8624,
   "latitude": 40.7607,
   "website": "https://www.nhl.com/utah/",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/9/95/Utah_Hockey_Club_2024-25_Logo.svg",
   "affiliate": "Tucson Roadrunners (AHL)"
 },
 {
   "team": "Boston Bruins",
   "moniker": ['Bruins', 'Boston'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "TD Garden",
   "location": "Boston, Massachusetts, USA",
   "longitude": -71.0621,
   "latitude": 42.3662,
   "website": "https://www.nhl.com/bruins",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/1/12/Boston_Bruins.svg",
   "affiliate": "Providence Bruins (AHL)"
 },
 {
   "team": "Buffalo Sabres",
   "moniker": ['Sabres', 'Buffalo'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "KeyBank Center",
   "location": "Buffalo, New York, USA",
   "longitude": -78.8766,
   "latitude": 42.874,
   "website": "https://www.nhl.com/sabres",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/9e/Buffalo_Sabres_Logo.svg",
   "affiliate": "Rochester Americans (AHL)"
 },
 {
   "team": "Calgary Flames",
   "moniker": ['Flames', 'Calgary'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "Scotiabank Saddledome",
   "location": "Calgary, Alberta, Canada",
   "longitude": -114.0518,
   "latitude": 51.0374,
   "website": "https://www.nhl.com/flames",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/6/61/Calgary_Flames_logo.svg",
   "affiliate": "Stockton Heat (AHL)"
 },
 {
   "team": "Carolina Hurricanes",
   "moniker": ['Hurricanes', 'Carolina'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "PNC Arena",
   "location": "Raleigh, North Carolina, USA",
   "longitude": -78.7213,
   "latitude": 35.8034,
   "website": "https://www.nhl.com/hurricanes",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/3/32/Carolina_Hurricanes.svg",
   "affiliate": "Chicago Wolves (AHL)"
 },
 {
   "team": "Chicago Blackhawks",
   "moniker": ['Blackhawks', 'Chicago'],
   "league": "NHL",
   "conference": "Central",
   "division": "Central",
   "stadium": "United Center",
   "location": "Chicago, Illinois, USA",
   "longitude": -87.6742,
   "latitude": 41.8807,
   "website": "https://www.nhl.com/blackhawks",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/2/29/Chicago_Blackhawks_logo.svg",
   "affiliate": "Rockford IceHogs (AHL)"
 },
 {
   "team": "Colorado Avalanche",
   "moniker": ['Avalanche', 'Colorado'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "Ball Arena",
   "location": "Denver, Colorado, USA",
   "longitude": -105.0077,
   "latitude": 39.7487,
   "website": "https://www.nhl.com/avalanche",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/45/Colorado_Avalanche_logo.svg",
   "affiliate": "Colorado Eagles (AHL)"
 },
 {
   "team": "Columbus Blue Jackets",
   "moniker": ['Blue Jackets', 'Columbus'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "Nationwide Arena",
   "location": "Columbus, Ohio, USA",
   "longitude": -83.006,
   "latitude": 39.9699,
   "website": "https://www.nhl.com/bluejackets",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/5/5d/Columbus_Blue_Jackets_logo.svg",
   "affiliate": "Cleveland Monsters (AHL)"
 },
 {
   "team": "Dallas Stars",
   "moniker": ['Stars', 'Dallas'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "American Airlines Center",
   "location": "Dallas, Texas, USA",
   "longitude": -96.8103,
   "latitude": 32.7903,
   "website": "https://www.nhl.com/stars",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/c/ce/Dallas_Stars_logo_%282013%29.svg",
   "affiliate": "Texas Stars (AHL)"
 },
 {
   "team": "Detroit Red Wings",
   "moniker": ['Red Wings', 'Detroit'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "Little Caesars Arena",
   "location": "Detroit, Michigan, USA",
   "longitude": -83.0554,
   "latitude": 42.341,
   "website": "https://www.nhl.com/redwings",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/e/e0/Detroit_Red_Wings_logo.svg",
   "affiliate": "Grand Rapids Griffins (AHL)"
 },
 {
   "team": "Edmonton Oilers",
   "moniker": ['Oilers', 'Edmonton'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "Rogers Place",
   "location": "Edmonton, Alberta, Canada",
   "longitude": -113.497,
   "latitude": 53.5461,
   "website": "https://www.nhl.com/oilers",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/4d/Logo_Edmonton_Oilers.svg",
   "affiliate": "Bakersfield Condors (AHL)"
 },
 {
   "team": "Florida Panthers",
   "moniker": ['Panthers', 'Florida'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "FLA Live Arena",
   "location": "Sunrise, Florida, USA",
   "longitude": -80.3256,
   "latitude": 26.1584,
   "website": "https://www.nhl.com/panthers",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/43/Florida_Panthers_2016_logo.svg",
   "affiliate": "Charlotte Checkers (AHL)"
 },
 {
   "team": "Los Angeles Kings",
   "moniker": ['Kings', 'Los Angeles'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "Crypto.com Arena",
   "location": "Los Angeles, California, USA",
   "longitude": -118.2673,
   "latitude": 34.043,
   "website": "https://www.nhl.com/kings",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/c/c4/Los_Angeles_Kings_2024_Logo.svg",
   "affiliate": "Ontario Reign (AHL)"
 },
 {
   "team": "Minnesota Wild",
   "moniker": ['Wild', 'Minnesota'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "Xcel Energy Center",
   "location": "Saint Paul, Minnesota, USA",
   "longitude": -93.1015,
   "latitude": 44.9442,
   "website": "https://www.nhl.com/wild",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/1/1b/Minnesota_Wild.svg",
   "affiliate": "Iowa Wild (AHL)"
 },
 {
   "team": "Montreal Canadiens",
   "moniker": ['Canadiens', 'Montreal'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "Bell Centre",
   "location": "Montreal, Quebec, Canada",
   "longitude": -73.5695,
   "latitude": 45.4961,
   "website": "https://www.nhl.com/canadiens",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/6/69/Montreal_Canadiens.svg",
   "affiliate": "Laval Rocket (AHL)"
 },
 {
   "team": "Nashville Predators",
   "moniker": ['Predators', 'Nashville'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "Bridgestone Arena",
   "location": "Nashville, Tennessee, USA",
   "longitude": -86.7785,
   "latitude": 36.1592,
   "website": "https://www.nhl.com/predators",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/9c/Nashville_Predators_Logo_%282011%29.svg",
   "affiliate": "Milwaukee Admirals (AHL)"
 },
 {
   "team": "New Jersey Devils",
   "moniker": ['Devils', 'New Jersey'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "Prudential Center",
   "location": "Newark, New Jersey, USA",
   "longitude": -74.1717,
   "latitude": 40.7334,
   "website": "https://www.nhl.com/devils",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/9f/New_Jersey_Devils_logo.svg",
   "affiliate": "Utica Comets (AHL)"
 },
 {
   "team": "New York Islanders",
   "moniker": ['Islanders', 'New York', 'NY'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "UBS Arena",
   "location": "Elmont, New York, USA",
   "longitude": -73.7138,
   "latitude": 40.6812,
   "website": "https://www.nhl.com/islanders",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/42/Logo_New_York_Islanders.svg",
   "affiliate": "Bridgeport Islanders (AHL)"
 },
 {
   "team": "New York Rangers",
   "moniker": ['Rangers', 'New York', 'NY'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "Madison Square Garden",
   "location": "New York City, New York, USA",
   "longitude": -73.9934,
   "latitude": 40.7505,
   "website": "https://www.nhl.com/rangers",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/a/ae/New_York_Rangers.svg",
   "affiliate": "Hartford Wolf Pack (AHL)"
 },
 {
   "team": "Ottawa Senators",
   "moniker": ['Senators', 'Ottawa'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "Canadian Tire Centre",
   "location": "Ottawa, Ontario, Canada",
   "longitude": -75.9276,
   "latitude": 45.2968,
   "website": "https://www.nhl.com/senators",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/b/b2/Ottawa_Senators_2020-2021_logo.svg",
   "affiliate": "Belleville Senators (AHL)"
 },
 {
   "team": "Philadelphia Flyers",
   "moniker": ['Flyers', 'Philadelphia'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "Wells Fargo Center",
   "location": "Philadelphia, Pennsylvania, USA",
   "longitude": -75.1719,
   "latitude": 39.9012,
   "website": "https://www.nhl.com/flyers",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/d/dc/Philadelphia_Flyers.svg",
   "affiliate": "Lehigh Valley Phantoms (AHL)"
 },
 {
   "team": "Pittsburgh Penguins",
   "moniker": ['Penguins', 'Pittsburgh'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "PPG Paints Arena",
   "location": "Pittsburgh, Pennsylvania, USA",
   "longitude": -79.9898,
   "latitude": 40.4394,
   "website": "https://www.nhl.com/penguins",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/c/c0/Pittsburgh_Penguins_logo_%282016%29.svg",
   "affiliate": "Wilkes-Barre/Scranton Penguins (AHL)"
 },
 {
   "team": "San Jose Sharks",
   "moniker": ['Sharks', 'San Jose'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "SAP Center at San Jose",
   "location": "San Jose, California, USA",
   "longitude": -121.9013,
   "latitude": 37.3327,
   "website": "https://www.nhl.com/sharks",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/3/37/SanJoseSharksLogo.svg",
   "affiliate": "San Jose Barracuda (AHL)"
 },
 {
   "team": "Seattle Kraken",
   "moniker": ['Kraken', 'Seattle'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "Climate Pledge Arena",
   "location": "Seattle, Washington, USA",
   "longitude": -122.354,
   "latitude": 47.6249,
   "website": "https://www.nhl.com/kraken",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/4/48/Seattle_Kraken_official_logo.svg",
   "affiliate": "Charlotte Checkers (AHL)"
 },
 {
   "team": "St. Louis Blues",
   "moniker": ['Blues', 'St. Louis', 'St Louis'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "Enterprise Center",
   "location": "St. Louis, Missouri, USA",
   "longitude": -90.2027,
   "latitude": 38.6268,
   "website": "https://www.nhl.com/blues",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/e/ed/St._Louis_Blues_logo.svg",
   "affiliate": "Springfield Thunderbirds (AHL)"
 },
 {
   "team": "Tampa Bay Lightning",
   "moniker": ['Lightning', 'Tampa Bay'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "Amalie Arena",
   "location": "Tampa, Florida, USA",
   "longitude": -82.4511,
   "latitude": 27.9425,
   "website": "https://www.nhl.com/lightning",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/3/31/Tampa_Bay_Lightning_2011.svg",
   "affiliate": "Syracuse Crunch (AHL)"
 },
 {
   "team": "Toronto Maple Leafs",
   "moniker": ['Maple Leafs', 'Toronto'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Atlantic",
   "stadium": "Scotiabank Arena",
   "location": "Toronto, Ontario, Canada",
   "longitude": -79.3791,
   "latitude": 43.6435,
   "website": "https://www.nhl.com/mapleleafs",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/b/b6/Toronto_Maple_Leafs_2016_logo.svg",
   "affiliate": "Toronto Marlies (AHL)"
 },
 {
   "team": "Vancouver Canucks",
   "moniker": ['Canucks', 'Vancouver'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "Rogers Arena",
   "location": "Vancouver, British Columbia, Canada",
   "longitude": -123.1188,
   "latitude": 49.2777,
   "website": "https://www.nhl.com/canucks",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/3/3a/Vancouver_Canucks_logo.svg",
   "affiliate": "Abbotsford Canucks (AHL)"
 },
 {
   "team": "Vegas Golden Knights",
   "moniker": ['Golden Knights', 'Vegas', 'Las Vegas'],
   "league": "NHL",
   "conference": "Western",
   "division": "Pacific",
   "stadium": "T-Mobile Arena",
   "location": "Paradise, Nevada, USA",
   "longitude": -115.1789,
   "latitude": 36.102,
   "website": "https://www.nhl.com/goldenknights",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/a/ac/Vegas_Golden_Knights_logo.svg",
   "affiliate": "Henderson Silver Knights (AHL)"
 },
 {
   "team": "Washington Capitals",
   "moniker": ['Capitals', 'Washington'],
   "league": "NHL",
   "conference": "Eastern",
   "division": "Metropolitan",
   "stadium": "Capital One Arena",
   "location": "Washington, D.C., USA",
   "longitude": -77.0209,
   "latitude": 38.8981,
   "website": "https://www.nhl.com/capitals",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/commons/2/2d/Washington_Capitals.svg",
   "affiliate": "Hershey Bears (AHL)"
 },
 {
   "team": "Winnipeg Jets",
   "moniker": ['Jets', 'Winnipeg'],
   "league": "NHL",
   "conference": "Western",
   "division": "Central",
   "stadium": "Canada Life Centre",
   "location": "Winnipeg, Manitoba, Canada",
   "longitude": -97.1437,
   "latitude": 49.8925,
   "website": "https://www.nhl.com/jets",
   "sport": "Hockey",
   "logo": "https://upload.wikimedia.org/wikipedia/en/9/93/Winnipeg_Jets_Logo_2011.svg",
   "affiliate": "Manitoba Moose (AHL)"
 },
 {
   "team": "Adirondack Thunder",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Cool Insuring Arena",
   "location": "Glens Falls, New York, USA",
   "longitude": -73.6438,
   "latitude": 43.3091,
   "website": "https://www.echlthunder.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New Jersey Devils"
 },
 {
   "team": "Allen Americans",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Allen Event Center",
   "location": "Allen, Texas, USA",
   "longitude": -96.6554,
   "latitude": 33.1298,
   "website": "https://allenamericans.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Ottawa Senators"
 },
 {
   "team": "Atlanta Gladiators",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Gas South Arena",
   "location": "Duluth, Georgia, USA",
   "longitude": -84.1496,
   "latitude": 33.9792,
   "website": "https://atlantagladiators.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Nashville Predators"
 },
 {
   "team": "Bloomington Bison",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Bloomington Ice Garden",
   "location": "Bloomington, Minnesota, USA",
   "longitude": -93.3085,
   "latitude": 44.8309,
   "website": "https://bloomingtonbisonhockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New York Rangers"
 },
 {
   "team": "Cincinnati Cyclones",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Heritage Bank Center",
   "location": "Cincinnati, Ohio, USA",
   "longitude": -84.5045,
   "latitude": 39.0978,
   "website": "https://cycloneshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New York Rangers"
 },
 {
   "team": "Florida Everblades",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Hertz Arena",
   "location": "Estero, Florida, USA",
   "longitude": -81.7772,
   "latitude": 26.4352,
   "website": "https://www.floridaeverblades.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Florida Panthers"
 },
 {
   "team": "Fort Wayne Komets",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Allen County War Memorial Coliseum",
   "location": "Fort Wayne, Indiana, USA",
   "longitude": -85.1384,
   "latitude": 41.0814,
   "website": "https://www.komets.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Edmonton Oilers"
 },
 {
   "team": "Greenville Swamp Rabbits",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Bon Secours Wellness Arena",
   "location": "Greenville, South Carolina, USA",
   "longitude": -82.391,
   "latitude": 34.8526,
   "website": "https://www.swamprabbits.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Los Angeles Kings"
 },
 {
   "team": "Idaho Steelheads",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Idaho Central Arena",
   "location": "Boise, Idaho, USA",
   "longitude": -116.203,
   "latitude": 43.6031,
   "website": "https://www.idahosteelheads.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Dallas Stars"
 },
 {
   "team": "Indy Fuel",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Indiana Farmers Coliseum",
   "location": "Indianapolis, Indiana, USA",
   "longitude": -86.1355,
   "latitude": 39.8287,
   "website": "https://www.indyfuelhockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Chicago Blackhawks"
 },
 {
   "team": "Iowa Heartlanders",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Heartland Events Center",
   "location": "Grand Island, Nebraska, USA",
   "longitude": -98.342,
   "latitude": 40.925,
   "website": "https://www.iowaheartlanders.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Minnesota Wild"
 },
 {
   "team": "Jacksonville Icemen",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "VyStar Veterans Memorial Arena",
   "location": "Jacksonville, Florida, USA",
   "longitude": -81.6433,
   "latitude": 30.3245,
   "website": "https://www.jacksonvilleicemen.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Buffalo Sabres"
 },
 {
   "team": "Kalamazoo Wings",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Wings Event Center",
   "location": "Kalamazoo, Michigan, USA",
   "longitude": -85.5897,
   "latitude": 42.2646,
   "website": "https://www.kwings.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Vancouver Canucks"
 },
 {
   "team": "Kansas City Mavericks",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Cable Dahmer Arena",
   "location": "Independence, Missouri, USA",
   "longitude": -94.3574,
   "latitude": 39.07,
   "website": "https://www.kcmavericks.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Seattle Kraken"
 },
 {
   "team": "Maine Mariners",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Cross Insurance Arena",
   "location": "Portland, Maine, USA",
   "longitude": -70.2572,
   "latitude": 43.651,
   "website": "https://www.marinersofmaine.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Boston Bruins"
 },
 {
   "team": "Newfoundland Growlers",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Mile One Centre",
   "location": "St. John's, Newfoundland and Labrador, Canada",
   "longitude": -52.7011,
   "latitude": 47.5685,
   "website": "https://www.nlgrowlers.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Toronto Maple Leafs"
 },
 {
   "team": "Norfolk Admirals",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Norfolk Scope",
   "location": "Norfolk, Virginia, USA",
   "longitude": -76.285,
   "latitude": 36.8465,
   "website": "https://www.norfolkadmirals.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Winnipeg Jets"
 },
 {
   "team": "Orlando Solar Bears",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Amway Center",
   "location": "Orlando, Florida, USA",
   "longitude": -81.3839,
   "latitude": 28.5392,
   "website": "https://www.orlandosolarbearshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Tampa Bay Lightning"
 },
 {
   "team": "Rapid City Rush",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Rushmore Plaza Civic Center",
   "location": "Rapid City, South Dakota, USA",
   "longitude": -103.231,
   "latitude": 44.0805,
   "website": "https://www.rapidcityrush.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Calgary Flames"
 },
 {
   "team": "Reading Royals",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Santander Arena",
   "location": "Reading, Pennsylvania, USA",
   "longitude": -75.922,
   "latitude": 40.3377,
   "website": "https://www.royalshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Philadelphia Flyers"
 },
 {
   "team": "South Carolina Stingrays",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "North Charleston Coliseum",
   "location": "North Charleston, South Carolina, USA",
   "longitude": -80.013,
   "latitude": 32.8731,
   "website": "https://www.stingrayshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Washington Capitals"
 },
 {
   "team": "Savannah Ghost Pirates",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Savannah Arena",
   "location": "Savannah, Georgia, USA",
   "longitude": -81.088,
   "latitude": 32.0762,
   "website": "https://www.ghostpirateshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Vegas Golden Knights"
 },
 {
   "team": "Tahoe Knight Monsters",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Lake Tahoe Ice Arena",
   "location": "Lake Tahoe, California, USA",
   "longitude": -119.9772,
   "latitude": 38.9404,
   "website": "https://knightmonstershockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Vegas Golden Knights"
 },
 {
   "team": "Toledo Walleye",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Huntington Center",
   "location": "Toledo, Ohio, USA",
   "longitude": -83.5389,
   "latitude": 41.651,
   "website": "https://www.toledowalleye.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Detroit Red Wings"
 },
 {
   "team": "Trois-Rivières Lions",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Le Nouveau Colisée",
   "location": "Trois-Rivières, Quebec, Canada",
   "longitude": -72.5562,
   "latitude": 46.3569,
   "website": "https://lions3r.com/en",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Montreal Canadiens"
 },
 {
   "team": "Tulsa Oilers",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "BOK Center",
   "location": "Tulsa, Oklahoma, USA",
   "longitude": -95.9962,
   "latitude": 36.1525,
   "website": "https://www.tulsaoilers.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Anaheim Ducks"
 },
 {
   "team": "Utah Grizzlies",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "Maverik Center",
   "location": "West Valley City, Utah, USA",
   "longitude": -111.9494,
   "latitude": 40.6916,
   "website": "https://utahgrizzlies.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Colorado Avalanche"
 },
 {
   "team": "Wheeling Nailers",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "WesBanco Arena",
   "location": "Wheeling, West Virginia, USA",
   "longitude": -80.7209,
   "latitude": 40.0653,
   "website": "https://www.wheelingnailers.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Pittsburgh Penguins"
 },
 {
   "team": "Wichita Thunder",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "INTRUST Bank Arena",
   "location": "Wichita, Kansas, USA",
   "longitude": -97.3301,
   "latitude": 37.6838,
   "website": "https://www.wichitathunder.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "San Jose Sharks"
 },
 {
   "team": "Worcester Railers",
   "moniker": "",
   "league": "ECHL",
   "conference": "",
   "division": "",
   "stadium": "DCU Center",
   "location": "Worcester, Massachusetts, USA",
   "longitude": -71.8022,
   "latitude": 42.2634,
   "website": "https://www.railershc.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New York Islanders"
 },
 {
   "team": "Abbotsford Canucks",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Abbotsford Centre",
   "location": "Abbotsford, British Columbia, Canada",
   "longitude": -122.3182,
   "latitude": 49.0319,
   "website": "https://abbotsford.canucks.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Vancouver Canucks"
 },
 {
   "team": "Bakersfield Condors",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Mechanics Bank Arena",
   "location": "Bakersfield, California, USA",
   "longitude": -119.0187,
   "latitude": 35.3722,
   "website": "https://www.bakersfieldcondors.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Edmonton Oilers"
 },
 {
   "team": "Belleville Senators",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "CAA Arena",
   "location": "Belleville, Ontario, Canada",
   "longitude": -77.3764,
   "latitude": 44.1788,
   "website": "https://bellevillesens.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Ottawa Senators"
 },
 {
   "team": "Bridgeport Islanders",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Webster Bank Arena",
   "location": "Bridgeport, Connecticut, USA",
   "longitude": -73.1894,
   "latitude": 41.1721,
   "website": "https://www.bridgeportislanders.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New York Islanders"
 },
 {
   "team": "Calgary Wranglers",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Scotiabank Saddledome",
   "location": "Calgary, Alberta, Canada",
   "longitude": -114.0518,
   "latitude": 51.0374,
   "website": "https://www.calgarywranglers.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Calgary Flames"
 },
 {
   "team": "Charlotte Checkers",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Bojangles' Coliseum",
   "location": "Charlotte, North Carolina, USA",
   "longitude": -80.822,
   "latitude": 35.2052,
   "website": "https://gocheckers.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Seattle Kraken"
 },
 {
   "team": "Chicago Wolves",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Allstate Arena",
   "location": "Chicago, Illinois, USA",
   "longitude": -87.8813,
   "latitude": 42.002,
   "website": "https://www.chicagowolves.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Carolina Hurricanes"
 },
 {
   "team": "Cleveland Monsters",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Rocket Mortgage FieldHouse",
   "location": "Cleveland, Ohio, USA",
   "longitude": -81.6883,
   "latitude": 41.4966,
   "website": "https://www.clevelandmonsters.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Columbus Blue Jackets"
 },
 {
   "team": "Coachella Valley Firebirds",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Acrisure Arena",
   "location": "Thousand Palms, California, USA",
   "longitude": -116.5453,
   "latitude": 33.8303,
   "website": "https://cvfirebirds.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Arizona Coyotes"
 },
 {
   "team": "Colorado Eagles",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Budweiser Events Center",
   "location": "Loveland, Colorado, USA",
   "longitude": -105.0745,
   "latitude": 40.3916,
   "website": "https://www.coloradoeagles.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Colorado Avalanche"
 },
 {
   "team": "Grand Rapids Griffins",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Van Andel Arena",
   "location": "Grand Rapids, Michigan, USA",
   "longitude": -85.6708,
   "latitude": 42.9634,
   "website": "https://griffinshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Detroit Red Wings"
 },
 {
   "team": "Hartford Wolf Pack",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "XL Center",
   "location": "Hartford, Connecticut, USA",
   "longitude": -72.6726,
   "latitude": 41.7688,
   "website": "https://www.hartfordwolfpack.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New York Rangers"
 },
 {
   "team": "Henderson Silver Knights",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Orleans Arena",
   "location": "Henderson, Nevada, USA",
   "longitude": -115.1756,
   "latitude": 36.0919,
   "website": "https://www.hendersonsilverknights.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Vegas Golden Knights"
 },
 {
   "team": "Hershey Bears",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Giant Center",
   "location": "Hershey, Pennsylvania, USA",
   "longitude": -76.6496,
   "latitude": 40.2857,
   "website": "https://www.hersheybears.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Washington Capitals"
 },
 {
   "team": "Iowa Wild",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Wells Fargo Arena",
   "location": "Des Moines, Iowa, USA",
   "longitude": -93.6208,
   "latitude": 41.5908,
   "website": "https://www.iowawild.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Minnesota Wild"
 },
 {
   "team": "Laval Rocket",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Place Bell",
   "location": "Laval, Quebec, Canada",
   "longitude": -73.7305,
   "latitude": 45.5613,
   "website": "https://www.rocketlaval.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Montreal Canadiens"
 },
 {
   "team": "Lehigh Valley Phantoms",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "PPL Center",
   "location": "Allentown, Pennsylvania, USA",
   "longitude": -75.4521,
   "latitude": 40.625,
   "website": "https://www.phantomshockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Philadelphia Flyers"
 },
 {
   "team": "Manitoba Moose",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Canada Life Centre",
   "location": "Winnipeg, Manitoba, Canada",
   "longitude": -97.1437,
   "latitude": 49.8925,
   "website": "https://moosehockey.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Winnipeg Jets"
 },
 {
   "team": "Milwaukee Admirals",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "UW–Milwaukee Panther Arena",
   "location": "Milwaukee, Wisconsin, USA",
   "longitude": -87.9172,
   "latitude": 43.0447,
   "website": "https://www.milwaukeeadmirals.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Nashville Predators"
 },
 {
   "team": "Ontario Reign",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Toyota Arena",
   "location": "Ontario, California, USA",
   "longitude": -117.5655,
   "latitude": 34.0718,
   "website": "https://www.ontarioreign.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Los Angeles Kings"
 },
 {
   "team": "Providence Bruins",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Dunkin' Donuts Center",
   "location": "Providence, Rhode Island, USA",
   "longitude": -71.4171,
   "latitude": 41.8302,
   "website": "https://www.providencebruins.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Boston Bruins"
 },
 {
   "team": "Rochester Americans",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Blue Cross Arena",
   "location": "Rochester, New York, USA",
   "longitude": -77.6038,
   "latitude": 43.1531,
   "website": "https://www.amerks.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Buffalo Sabres"
 },
 {
   "team": "Rockford IceHogs",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "BMO Harris Bank Center",
   "location": "Rockford, Illinois, USA",
   "longitude": -89.407,
   "latitude": 42.0934,
   "website": "https://www.icehogs.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Chicago Blackhawks"
 },
 {
   "team": "San Diego Gulls",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Pechanga Arena",
   "location": "San Diego, California, USA",
   "longitude": -117.2123,
   "latitude": 32.7554,
   "website": "https://www.sandiegogulls.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Anaheim Ducks"
 },
 {
   "team": "San Jose Barracuda",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "SAP Center",
   "location": "San Jose, California, USA",
   "longitude": -121.9013,
   "latitude": 37.3327,
   "website": "https://www.sjbarracuda.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "San Jose Sharks"
 },
 {
   "team": "Springfield Thunderbirds",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "MassMutual Center",
   "location": "Springfield, Massachusetts, USA",
   "longitude": -72.5813,
   "latitude": 42.0998,
   "website": "https://www.springfieldthunderbirds.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "St. Louis Blues"
 },
 {
   "team": "Syracuse Crunch",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Upstate Medical University Arena",
   "location": "Syracuse, New York, USA",
   "longitude": -76.1451,
   "latitude": 43.0448,
   "website": "https://www.syracusecrunch.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Tampa Bay Lightning"
 },
 {
   "team": "Texas Stars",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "H-E-B Center at Cedar Park",
   "location": "Cedar Park, Texas, USA",
   "longitude": -97.8253,
   "latitude": 30.5252,
   "website": "https://www.texasstars.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Dallas Stars"
 },
 {
   "team": "Toronto Marlies",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Coca-Cola Coliseum",
   "location": "Toronto, Ontario, Canada",
   "longitude": -79.4183,
   "latitude": 43.6332,
   "website": "https://marlies.ca/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Toronto Maple Leafs"
 },
 {
   "team": "Tucson Roadrunners",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Tucson Convention Center",
   "location": "Tucson, Arizona, USA",
   "longitude": -110.9715,
   "latitude": 32.2226,
   "website": "https://www.tucsonroadrunners.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Utah Hockey Club"
 },
 {
   "team": "Utica Comets",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Adirondack Bank Center",
   "location": "Utica, New York, USA",
   "longitude": -75.2233,
   "latitude": 43.0979,
   "website": "https://www.uticacomets.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "New Jersey Devils"
 },
 {
   "team": "Wilkes-Barre/Scranton Penguins",
   "moniker": "",
   "league": "AHL",
   "conference": "",
   "division": "",
   "stadium": "Mohegan Sun Arena at Casey Plaza",
   "location": "Wilkes-Barre Township, Pennsylvania, USA",
   "longitude": -75.8245,
   "latitude": 41.2481,
   "website": "https://www.wbspenguins.com/",
   "sport": "Hockey",
   "logo": "",
   "affiliate": "Pittsburgh Penguins"
 }
]