football_teams = [
  {
    'team': 'Arizona Cardinals',
    'moniker': ['Arizona',
                'Cardinals',],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC West',
    'stadium': 'State Farm Stadium',
    'location': 'Glendale, Arizona',
    'longitude': -112.263,
    'latitude': 33.5276,
    'website': 'https://www.azcardinals.com/',
    'sport': 'Football',
    'logo': "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg"
  },
  {
    'team': 'Buffalo Bills',
    'moniker': ['Buffalo',
                'Bills'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC East',
    'stadium': 'Highmark Stadium',
    'location': 'Orchard Park, New York',
    'longitude': -78.787,
    'latitude': 42.7738,
    'website': 'https://www.buffalobills.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg',
  },
  {
    'team': 'Carolina Panthers',
    'moniker': ['Carolina',
                'Panthers'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC South',
    'stadium': 'Bank of America Stadium',
    'location': 'Charlotte, North Carolina',
    'longitude': -80.8537,
    'latitude': 35.2251,
    'website': 'https://www.panthers.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg'
  },
  {
    'team': 'Miami Dolphins',
    'moniker': ['Miami',
                'Dolphins'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC East',
    'stadium': 'Hard Rock Stadium',
    'location': 'Miami Gardens, Florida',
    'longitude': -80.2389,
    'latitude': 25.957,
    'website': 'https://www.miamidolphins.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg'
  },
  {
    'team': 'New England Patriots',
    'moniker': ['New England',
                'Patriots'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC East',
    'stadium': 'Gillette Stadium',
    'location': 'Foxborough, Massachusetts',
    'longitude': -71.2643,
    'latitude': 42.0909,
    'website': 'https://www.patriots.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg'
  },
  {
    'team': 'Philadelphia Eagles',
    'moniker': ['Philadelphia',
                'Philly',
                'Eagles'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC East',
    'stadium': 'Lincoln Financial Field',
    'location': 'Philadelphia, Pennsylvania',
    'longitude': -75.1674,
    'latitude': 39.9008,
    'website': 'https://www.philadelphiaeagles.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg'
  },
  {
    'team': 'Atlanta Falcons',
    'moniker': ['Atlanta',
                'Falcons'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC South',
    'stadium': 'Mercedes-Benz Stadium',
    'location': 'Atlanta, Georgia',
    'longitude': -84.4011,
    'latitude': 33.7554,
    'website': 'https://www.atlantafalcons.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg'
  },
  {
    'team': 'Baltimore Ravens',
    'moniker': ['Baltimore',
                'Ravens'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC North',
    'stadium': 'M&T Bank Stadium',
    'location': 'Baltimore, Maryland',
    'longitude': -76.6227,
    'latitude': 39.278,
    'website': 'https://www.baltimoreravens.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg'
  },
  {
    'team': 'Chicago Bears',
    'moniker': ['Chicago',
                'Bears'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC North',
    'stadium': 'Soldier Field',
    'location': 'Chicago, Illinois',
    'longitude': -87.6166,
    'latitude': 41.8623,
    'website': 'https://www.chicagobears.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/1/15/Chicago_Bears_logo_primary.svg'
  },
  {
    'team': 'Cincinnati Bengals',
    'moniker': ['Cincinnati',
                'Bengals'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC North',
    'stadium': 'Paul Brown Stadium',
    'location': 'Cincinnati, Ohio',
    'longitude': -84.516,
    'latitude': 39.095,
    'website': 'https://www.bengals.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg'
  },
  {
    'team': 'Cleveland Browns',
    'moniker': ['Cleveland',
                'Browns'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC North',
    'stadium': 'FirstEnergy Stadium',
    'location': 'Cleveland, Ohio',
    'longitude': -81.6954,
    'latitude': 41.5066,
    'website': 'https://www.clevelandbrowns.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg'
  },
  {
    'team': 'Dallas Cowboys',
    'moniker': ['Dallas',
                'Cowboys'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC East',
    'stadium': 'AT&T Stadium',
    'location': 'Arlington, Texas',
    'longitude': -97.0929,
    'latitude': 32.7473,
    'website': 'https://www.dallascowboys.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg'
  },
  {
    'team': 'Denver Broncos',
    'moniker': ['Denver',
                'Broncos'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC West',
    'stadium': 'Empower Field at Mile High',
    'location': 'Denver, Colorado',
    'longitude': -105.0201,
    'latitude': 39.7439,
    'website': 'https://www.denverbroncos.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg',
  },
  {
    'team': 'Detroit Lions',
    'moniker': ['Detroit',
                'Lions'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC North',
    'stadium': 'Ford Field',
    'location': 'Detroit, Michigan',
    'longitude': -83.0458,
    'latitude': 42.3401,
    'website': 'https://www.detroitlions.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg'
  },
  {
    'team': 'Green Bay Packers',
    'moniker': ['Green Bay',
                'Packers'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC North',
    'stadium': 'Lambeau Field',
    'location': 'Green Bay, Wisconsin',
    'longitude': -88.0634,
    'latitude': 44.5013,
    'website': 'https://www.packers.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg'
  },
  {
    'team': 'Houston Texans',
    'moniker': ['Houston',
                'Texans'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC South',
    'stadium': 'NRG Stadium',
    'location': 'Houston, Texas',
    'longitude': -95.4109,
    'latitude': 29.6847,
    'website': 'https://www.houstontexans.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg'
  },
  {
    'team': 'Indianapolis Colts',
    'moniker': ['Indianapolis',
                'Indy',
                'Colts'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC South',
    'stadium': 'Lucas Oil Stadium',
    'location': 'Indianapolis, Indiana',
    'longitude': -86.1646,
    'latitude': 39.7601,
    'website': 'https://www.colts.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg'
  },
  {
    'team': 'Jacksonville Jaguars',
    'moniker': ['Jacksonville',
                'Jaguars'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC South',
    'stadium': 'TIAA Bank Field',
    'location': 'Jacksonville, Florida',
    'longitude': -81.638,
    'latitude': 30.3241,
    'website': 'https://www.jaguars.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg'
  },
  {
    'team': 'Kansas City Chiefs',
    'moniker': ['Kansas City',
                'Chiefs'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC West',
    'stadium': 'Arrowhead Stadium',
    'location': 'Kansas City, Missouri',
    'longitude': -94.4839,
    'latitude': 39.0517,
    'website': 'https://www.chiefs.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg'
  },
  {
    'team': 'Las Vegas Raiders',
    'moniker': ['Las Vegas',
                'Vegas',
                'Raiders'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC West',
    'stadium': 'Allegiant Stadium',
    'location': 'Paradise, Nevada',
    'longitude': -115.1541,
    'latitude': 36.0907,
    'website': 'https://www.raiders.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/4/48/Las_Vegas_Raiders_logo.svg',
  },
  {
    'team': 'Los Angeles Chargers',
    'moniker': ['Los Angeles',
                'LA',
                'Chargers'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC West',
    'stadium': 'SoFi Stadium',
    'location': 'Inglewood, California',
    'longitude': -118.3287,
    'latitude': 33.9534,
    'website': 'https://www.chargers.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Los_Angeles_Chargers_logo.svg'
  },
  {
    'team': 'Los Angeles Rams',
    'moniker': ['Log Angeles',
                'LA',
                'LA Rams',
                'Rams'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC West',
    'stadium': 'SoFi Stadium',
    'location': 'Inglewood, California',
    'longitude': -118.3287,
    'latitude': 33.9534,
    'website': 'https://www.therams.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg'
  },
  {
    'team': 'Minnesota Vikings',
    'moniker': ['Minnesota',
                'Vikings'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC North',
    'stadium': 'U.S. Bank Stadium',
    'location': 'Minneapolis, Minnesota',
    'longitude': -93.2667,
    'latitude': 44.9738,
    'website': 'https://www.vikings.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg'
  },
  {
    'team': 'New Orleans Saints',
    'moniker': ['New Orleans',
                'Saints'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC South',
    'stadium': 'Caesars Superdome',
    'location': 'New Orleans, Louisiana',
    'longitude': -90.081,
    'latitude': 29.9511,
    'website': 'https://www.neworleanssaints.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg'
  },
  {
    'team': 'New York Giants',
    'moniker': ['New York',
                'NY',
                'Giants'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC East',
    'stadium': 'MetLife Stadium',
    'location': 'East Rutherford, New Jersey',
    'longitude': -74.074,
    'latitude': 40.812,
    'website': 'https://www.giants.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg'
  },
  {
    'team': 'New York Jets',
    'moniker': ['New York',
                'NY',
                'Jets'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC East',
    'stadium': 'MetLife Stadium',
    'location': 'East Rutherford, New Jersey',
    'longitude': -74.074,
    'latitude': 40.812,
    'website': 'https://www.newyorkjets.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/6/69/New_York_Jets_2024.svg'
  },
  {
    'team': 'Pittsburgh Steelers',
    'moniker': ['Pittsburgh',
                'Steelers'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC North',
    'stadium': 'Heinz Field',
    'location': 'Pittsburgh, Pennsylvania',
    'longitude': -80.0164,
    'latitude': 40.4468,
    'website': 'https://www.steelers.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg'
  },
  {
    'team': 'San Francisco 49ers',
    'moniker': ['San Francisco',
                '49ers',
                'Forty Niners',
                'Niners',
                'Forty-Niners',
                '49'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC West',
    'stadium': "Levi's Stadium",
    'location': 'Santa Clara, California',
    'longitude': -121.9697,
    'latitude': 37.403,
    'website': 'https://www.49ers.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg'
  },
  {
    'team': 'Seattle Seahawks',
    'moniker': ['Seattle',
                'Seahawks'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC West',
    'stadium': 'Lumen Field',
    'location': 'Seattle, Washington',
    'longitude': -122.3316,
    'latitude': 47.5952,
    'website': 'https://www.seahawks.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg'
  },
  {
    'team': 'Tampa Bay Buccaneers',
    'moniker': ['Tampa Bay',
                'Tampa',
                'Buccaneers',
                'Buccs'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC South',
    'stadium': 'Raymond James Stadium',
    'location': 'Tampa, Florida',
    'longitude': -82.5048,
    'latitude': 27.9759,
    'website': 'https://www.buccaneers.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg'
  },
  {
    'team': 'Tennessee Titans',
    'moniker': ['Tennessee',
                'Titans'],
    'league': 'NFL',
    'conference': 'AFC',
    'division': 'AFC South',
    'stadium': 'Nissan Stadium',
    'location': 'Nashville, Tennessee',
    'longitude': -86.77,
    'latitude': 36.1664,
    'website': 'https://www.tennesseetitans.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg'
  },
  {
    'team': 'Washington Commanders',
    'moniker': ['Washington',
                'DC',
                'Commanders'],
    'league': 'NFL',
    'conference': 'NFC',
    'division': 'NFC East',
    'stadium': 'FedExField',
    'location': 'Landover, Maryland',
    'longitude': -76.8644,
    'latitude': 38.9076,
    'website': 'https://www.commanders.com/',
    'sport': 'Football',
    'logo': 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Washington_Commanders_logo.svg'
  },
  # {
  #   'team': 'Arlington Renegades',
  #   'moniker': ['Arlington',
  #               'Renegades'],
  #   'league': 'UFL',
  #   'conference': 'XFL',
  #   'division': 'N/A',
  #   'stadium': 'Choctaw Stadium',
  #   'location': 'Arlington, Texas',
  #   'longitude': -97.097,
  #   'latitude': 32.7357,
  #   'website': 'https://www.theufl.com/teams/arlington',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/commons/2/21/Arlington_Renegades_logo.png'
  # },
  # {
  #   'team': 'Birmingham Stallions',
  #   'moniker': ['Birmingham',
  #               'Stallions'],
  #   'league': 'UFL',
  #   'conference': 'USFL',
  #   'division': 'N/A',
  #   'stadium': 'Protective Stadium',
  #   'location': 'Birmingham, Alabama',
  #   'longitude': -86.8114,
  #   'latitude': 33.5074,
  #   'website': 'https://www.theufl.com/teams/birmingham',
  #   'sport': 'Football',
  #   'logo': "https://upload.wikimedia.org/wikipedia/en/9/9a/Birmingham_Stallions_logo.svg"
  # },
  # {
  #   'team': 'DC Defenders',
  #   'moniker': ['Washington DC',
  #               'DC',
  #               'D.C.',
  #               'Washington D.C.',
  #               'Defenders'],
  #   'league': 'UFL',
  #   'conference': 'XFL',
  #   'division': 'N/A',
  #   'stadium': 'Audi Field',
  #   'location': 'Washington, D.C.',
  #   'longitude': -77.0126,
  #   'latitude': 38.8765,
  #   'website': 'https://www.theufl.com/teams/dc',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/commons/a/aa/DC_Defenders_logo.png',
  # },
  # {
  #   'team': 'Houston Roughnecks',
  #   'moniker': ['Houston',
  #               'Roughnecks'],
  #   'league': 'UFL',
  #   'conference': 'USFL',
  #   'division': 'N/A',
  #   'stadium': 'Rice Stadium',
  #   'location': 'Houston, Texas',
  #   'longitude': -95.4027,
  #   'latitude': 29.7184,
  #   'website': 'https://www.theufl.com/teams/houston',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/en/d/d9/Houston_Roughnecks_logo_%282022%29.png'
  # },
  # {
  #   'team': 'Memphis Showboats',
  #   'moniker': ['Memphis',
  #               'Showboats'],
  #   'league': 'UFL',
  #   'conference': 'USFL',
  #   'division': 'N/A',
  #   'stadium': 'Simmons Bank Liberty Stadium',
  #   'location': 'Memphis, Tennessee',
  #   'longitude': -90.0495,
  #   'latitude': 35.1385,
  #   'website': 'https://www.theufl.com/teams/memphis',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/en/c/c4/Memphis_Showboats.png',
  # },
  # {
  #   'team': 'Michigan Panthers',
  #   'moniker': ['Michigan',
  #               'Panthers'],
  #   'league': 'UFL',
  #   'conference': 'USFL',
  #   'division': 'N/A',
  #   'stadium': 'Ford Field',
  #   'location': 'Detroit, Michigan',
  #   'longitude': -83.0458,
  #   'latitude': 42.3401,
  #   'website': 'https://www.theufl.com/teams/michigan',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/en/7/71/Michigan_Panthers_transparent.png'
  # },
  # {
  #   'team': 'San Antonio Brahmas',
  #   'moniker': ['San Antonio',
  #               'Brahmas'],
  #   'league': 'UFL',
  #   'conference': 'XFL',
  #   'division': 'N/A',
  #   'stadium': 'Alamodome',
  #   'location': 'San Antonio, Texas',
  #   'longitude': -98.4786,
  #   'latitude': 29.4167,
  #   'website': 'https://www.theufl.com/teams/san-antonio',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/en/2/22/San_Antonio_Brahmas_logo.png'
  # },
  # {
  #   'team': 'St. Louis Battlehawks',
  #   'moniker': ['St. Louis',
  #               'St Louis',
  #               'Battlehawks'],
  #   'league': 'UFL',
  #   'conference': 'XFL',
  #   'division': 'N/A',
  #   'stadium': "The Dome at America's Center",
  #   'location': 'St. Louis, Missouri',
  #   'longitude': -90.2003,
  #   'latitude': 38.6327,
  #   'website': 'https://www.theufl.com/teams/st-louis',
  #   'sport': 'Football',
  #   'logo': 'https://upload.wikimedia.org/wikipedia/en/9/9c/St._Louis_Battlehawks_logo.png'
  # }
]